services:
  api:
    build: ./backend
    depends_on:
      database:
        condition: service_healthy # Wait for database to be healthy
      mqttbroker:
        condition: service_started
    volumes:
      - ./backend:/app
      - ./backend/dockerbuild:/build
    networks:
      - app-network
      - db-network

  database:
    image: postgres:15
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: kirixo
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: arkanovadb
    volumes:
      - ./db/ArkaNova.sql:/docker-entrypoint-initdb.d/ArkaNova.sql
    networks:
      - db-network
    healthcheck: # Add healthcheck for PostgreSQL
      test: [ "CMD-SHELL", "pg_isready -U kirixo -d arkanovadb -q" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
  ngrok:
    image: ngrok/ngrok:latest
    command: http api:4925 --url=literate-vastly-pony.ngrok-free.app
    environment: 
      NGROK_AUTHTOKEN: 2hAY34ptDMfqzhti7skGACsKB5c_64p8iSLUv9Q5TJv7ckLfV
    networks:
      - app-network
  mqttbroker:
    build: ./mosquitto
    ports: 
      - "1883:1883"
    networks:
      - app-network
networks:
  app-network:
  db-network:
